apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: kube-prometheus-stack
  name: kubflow-rules
  namespace: kubflow
spec:
  groups:
    - name: kubflow
      rules:
        - alert: down
          expr: up == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary:  Promethus target missing {{$labels.instance}}